spring.application.name=rota-verde

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm562801
spring.datasource.password=041198
spring.flyway.baselineOnMigrate=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-stacktracer=never
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=never