spring.application.name=rota-verde

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.flyway.baselineOnMigrate=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.error.include-stacktracer=never
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=never

my.secret.value=${JWT.SECRET:----}